DROP TABLE IF EXISTS hello_world_greeting;

CREATE TABLE hello_world_greeting (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        greeting varchar(255) not null,
        sender varchar(255) not null,
        recipient varchar(255) not null
);

INSERT INTO hello_world_greeting (greeting, sender, recipient) VALUES ('Hello World', 'Everyone', 'Valerie');
INSERT INTO hello_world_greeting (greeting, sender, recipient) VALUES ('Howdy', 'Yall', 'Val');
INSERT INTO hello_world_greeting (greeting, sender, recipient) VALUES ('Hey', 'Buddy', 'Val');
INSERT INTO hello_world_greeting (greeting, sender, recipient) VALUES ('Yo', 'Bro', 'Val');